import React from "react";
import DefaultLayout from "../layouts/DefaultLayout";

export default function HomePage() {
  return (
    <DefaultLayout>
      <div>dsdasdsad ouais re</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
      <div>dsdasdsad</div>
    </DefaultLayout>
  );
}
